training_data = [
    # ==================
    # PYTHON BASICS
    # ==================
    "python is a programming language",
    "python is easy to learn for beginners",
    "python is used for artificial intelligence",
    "python is used for machine learning",
    "python is used for web development",
    "python is used for data science",
    "python has simple and clean syntax",
    "python was created by guido van rossum",
    "python is an interpreted language",
    "python supports object oriented programming",
    "python uses indentation instead of brackets",
    "python is free and open source",
    "python runs on windows mac and linux",
    "python has a large community of developers",
    "python is popular for automation and scripting",

    # ==================
    # PYTHON CONCEPTS
    # ==================
    "variables store data in programming",
    "functions are reusable blocks of code",
    "loops repeat code multiple times",
    "if statements make decisions in code",
    "lists store multiple values in python",
    "dictionaries store key value pairs",
    "classes are blueprints for objects",
    "objects are instances of classes",
    "algorithms are step by step instructions",
    "debugging is finding and fixing errors in code",
    "comments explain what code does",
    "indentation is important in python",
    "strings are sequences of characters",
    "integers are whole numbers in programming",
    "floats are decimal numbers in programming",
    "booleans are true or false values",
    "tuples are immutable lists in python",
    "sets store unique values in python",
    "modules are files containing python code",
    "libraries are collections of modules",
    "pip is the package manager for python",
    "exceptions are errors that occur during runtime",
    "try and except handle errors in python",
    "lambda is an anonymous function in python",
    "list comprehension creates lists in one line",
    "generators are functions that yield values",
    "decorators modify functions in python",
    "recursion is a function calling itself",
    "inheritance allows classes to reuse code",
    "polymorphism allows objects to take many forms",
    "encapsulation hides data inside classes",

    # ==================
    # HOW TO LEARN
    # ==================
    "to learn coding start with the basics",
    "practice coding every single day",
    "build projects to learn programming faster",
    "reading documentation helps you learn",
    "solving problems improves coding skills",
    "learn one programming language at a time",
    "understanding errors helps you improve",
    "google is a programmers best friend",
    "stack overflow helps programmers solve problems",
    "youtube has free coding tutorials",
    "consistency is key to learning programming",
    "start small and grow your skills gradually",
    "coding bootcamps teach programming intensively",
    "open source projects help you learn from others",
    "pair programming helps you learn faster",
    "code review improves your programming skills",
    "write clean and readable code always",
    "test your code before deploying it",
    "version control helps manage your code",
    "git is essential for every developer",

    # ==================
    # AI AND ML
    # ==================
    "neural networks learn from data",
    "artificial intelligence finds patterns in data",
    "machine learning is a subset of artificial intelligence",
    "deep learning uses neural networks",
    "training data teaches the model patterns",
    "neural networks are inspired by human brain",
    "artificial intelligence can learn and improve",
    "data is the fuel of artificial intelligence",
    "models learn by minimizing loss",
    "loss measures how wrong the model is",
    "gradient descent optimizes the model weights",
    "backpropagation computes gradients in neural networks",
    "transformers are powerful neural network architectures",
    "attention mechanism helps model focus on important words",
    "embeddings convert words to numbers",
    "tokens are units of text in language models",
    "vocabulary is the set of known words",
    "training makes the model smarter over time",
    "overfitting means model memorized training data",
    "underfitting means model did not learn enough",
    "supervised learning uses labeled data",
    "unsupervised learning finds patterns without labels",
    "reinforcement learning learns from rewards",
    "convolutional networks are used for images",
    "recurrent networks process sequential data",
    "gpt is a generative pretrained transformer",
    "bert is a bidirectional encoder representation",
    "large language models are trained on huge datasets",
    "fine tuning adapts pretrained models to new tasks",
    "transfer learning reuses knowledge from other models",
    "natural language processing handles text data",
    "computer vision handles image data",
    "speech recognition converts audio to text",
    "generative ai creates new content from patterns",
    "chatbots use ai to have conversations",

    # ==================
    # COMPUTER SCIENCE
    # ==================
    "computers process data very fast",
    "code is instructions for computers",
    "programming is the art of writing code",
    "software is a collection of programs",
    "hardware is the physical part of computers",
    "memory stores data temporarily in computers",
    "cpu is the brain of the computer",
    "gpu accelerates parallel computations",
    "binary is the language of computers",
    "internet connects computers around the world",
    "databases store large amounts of data",
    "servers serve data to clients",
    "apis allow programs to communicate",
    "open source software is free to use",
    "version control tracks changes in code",
    "git is a popular version control system",
    "linux is a popular operating system for developers",
    "cloud computing provides resources over the internet",
    "docker containers package applications",
    "kubernetes manages containerized applications",
    "rest apis use http to communicate",
    "json is a data format used in apis",
    "sql is used to query databases",
    "nosql databases store unstructured data",
    "encryption protects data from unauthorized access",
    "cybersecurity protects systems from attacks",
    "networking connects computers together",
    "operating systems manage computer resources",
    "compilers translate code to machine language",
    "interpreters execute code line by line",

    # ==================
    # WEB DEVELOPMENT
    # ==================
    "html is the structure of web pages",
    "css is the style of web pages",
    "javascript makes web pages interactive",
    "react is a popular javascript framework",
    "nodejs runs javascript on the server",
    "django is a python web framework",
    "flask is a lightweight python web framework",
    "frontend development builds user interfaces",
    "backend development builds server logic",
    "fullstack development covers frontend and backend",
    "databases store website data",
    "http is the protocol of the web",
    "https is secure http",
    "browsers render html css and javascript",
    "responsive design works on all screen sizes",

    # ==================
    # GENERAL KNOWLEDGE
    # ==================
    "the earth orbits around the sun",
    "water is made of hydrogen and oxygen",
    "humans need food water and shelter to survive",
    "science is the study of the natural world",
    "mathematics is the language of the universe",
    "history teaches us about the past",
    "languages help humans communicate with each other",
    "music is a universal language",
    "art is a form of human expression",
    "books contain knowledge and stories",
    "the internet changed how humans share information",
    "smartphones connect people around the world",
    "electricity powers modern civilization",
    "the sun provides energy to earth",
    "plants convert sunlight to food through photosynthesis",
    "the human brain has billions of neurons",
    "dna contains the genetic code of living things",
    "evolution explains how species change over time",
    "gravity keeps planets in orbit",
    "the speed of light is very fast",

    # ==================
    # MOTIVATIONAL
    # ==================
    "every expert was once a beginner",
    "learning takes time and patience",
    "mistakes are part of the learning process",
    "never give up on your goals",
    "small progress every day leads to big results",
    "hard work beats talent when talent does not work hard",
    "the best time to start learning is now",
    "believe in yourself and your abilities",
    "challenges make you stronger and smarter",
    "success comes to those who never stop learning",
    # ==================
    # CONVERSATIONS
    # ==================
    "hello i am jonje personal ai",
    "hi there i am your personal ai assistant",
    "hey i am here to help you",
    "what is python python is a programming language",
    "what is ai ai is artificial intelligence",
    "what is machine learning machine learning is a subset of ai",
    "what is deep learning deep learning uses neural networks",
    "what is coding coding is writing instructions for computers",
    "who are you i am jonje personal ai assistant",
    "who created you jonje created me",
    "what is your name i am jonje personal ai",
    "who is jonje jonje is my creator",
    "how to learn python practice coding every day",
    "how to learn ai study neural networks and data",
    "how to learn coding start with the basics",
    "hello how are you i am ready to help",
    "hi what can you do i can answer questions",
    "what do you know i know about python and ai",
    "teach me python python is easy to learn",
    "teach me ai ai learns patterns from data",
]
